export const VIEW_SELECTOR = {
    FIND_POST_OVERVIEW: 'findPostOverview',
    FIND_IDEA_OVERVIEW: 'findIdeaOverview',
    FIND_POST_DETAIL: 'findPostDetail',
    FIND_POST_PATCH_DETAIL: 'findPostPatchDetail',
    FIND_SIPER: 'findSiper',
    FIND_POST_COMMENTS: 'findPostComments',
    FIND_POST_AUTHOR_IDEAS: 'findPostAuthorIdeas',
    FIND_TOPIC_DETAIL: 'findTopicDetail',
    FIND_DISCUSSIONS: 'findDiscussions',
    FIND_DISCUSSION_DETAIL: 'findDiscussionDetail',
    FIND_DISCUSSION_COMMENTS: 'findDiscussionComments',
    SEARCH_TOPIC: 'searchTopic',
    SEARCH_MAKERS: 'searchUsers',
    CREATE_COMMENT: 'createComment',
    CREATE_REPLY: 'createReply',
};
